### ISSUE TITLE
Inventory player model becoming invisible when the player's camera is pointing downward

### ISSUE THREAD

**Issue by Oranamous** [bradleyq/stable_player_display#2]
Likely due to the fact that IViewRotMat is the same in gui as in the world, the fix is simple.
Change line 79 in the vertex shader from:
`if (dim.x != 64 || dim.y != 64) {`
To:
`if (ProjMat[3][2] == -2.0 || dim.x != 64 || dim.y != 64) {`
This fixed the issue on my end and doesn't appear to cause any additional bugs.

**Comment by bradleyq** [comment]
I do not repro this but this is a good addition anyway. resloved.
