### ISSUE TITLE
Issues with sodium

### ISSUE THREAD

**Issue by tomalbrc** [bradleyq/stable_player_display#3]
Some sides of the model don't seem to be assigned the way they should when using sodium with 1.20
![image](https://github.com/bradleyq/stable_player_display/assets/16482036/0a018e0c-3624-4938-850c-5b90e6c17be8)
![image](https://github.com/bradleyq/stable_player_display/assets/16482036/a0e8c777-ad2a-4d03-9353-72dcf10270bb)

Is there a solution for this? I noticed some servers like OR don't seem to have that problem

**Comment by bradleyq** [comment]
no idea, just in case, could you drop your hardware and software specs? Or just drop a f3 menu.

**Comment by Hellaweird** [comment]
Same issue here! 

Specs: Core i7-10700k, NVIDIA RTX 2027 SUPER, 32GB DDR4. 
Running windows 10, and latest firmware update for nvidia.

**Comment by bradleyq** [comment]
this seems like a sodium vertex ordering problem. Solving this will take some work...

**Comment by tomalbrc** [comment]
Ok so, sodium messes with the order of the faces, a workaround would be to look at the UV0 and detect which side is the correct/current one by checking the range of it

```
if ((UV0.x >= 8.f/64.f && UV0.x >= 16.f/64.f && UV0.y >= 8.f/64.f && UV0.y >= 16.f/64.f) || (UV0.x >= 40.f/64.f && UV0.x >= 48.f/64.f && UV0.y >= 8.f/64.f && UV0.y >= 16.f/64.f)) {
        // its the front side 
    }
```
something like this could work

**Comment by tomalbrc** [comment]
I just tested this by modifying a diff shader with the same issue (Denizen-Player-Models, its spawn order dependent tho),
seems to work nicely

~~Edit: Oh it may only work for this spawn dependent shader since you can't tell which body part should be rendered without looking at gl_VertexID~~ never mind, could work since you use positions to identify the body part

**Comment by Creeperz653** [comment]
Any news

**Comment by bradleyq** [comment]
resolved. @Creeperz653  please test and report back. I will close when confirmed.

**Comment by Creeperz653** [comment]
![2024-02-04_20 26 21](https://github.com/bradleyq/stable_player_display/assets/76449952/087e1fc9-3adf-466d-9c44-a257b2639f2a)
![2024-02-04_20 26 29](https://github.com/bradleyq/stable_player_display/assets/76449952/2664769c-6be2-4167-a625-d1a6f865fa6b)

No

**Comment by Creeperz653** [comment]
https://github.com/CreeperNation/Creepernation-Website/blob/main/assets/resourcepacks/CreeperNation.zip
rp if download required

**Comment by Creeperz653** [comment]
i just updated the shader that you updated (im using model engine)

**Comment by Creeperz653** [comment]
![2024-02-04_21 06 25](https://github.com/bradleyq/stable_player_display/assets/76449952/864b5352-7b0f-4a8b-9401-ff3428968688)
my skin lol

**Comment by bradleyq** [comment]
hm ok. I tested with your rp. It seems like your playerhead custom models are out of date. Also, make sure your summon scripts are correct. It looks like the arm textures are being loaded for every part. The texture orientation is correct though which is what I am fixing. You can sanity check by trying the sample summon commands in the repo readme.

**Comment by Creeperz653** [comment]
> hm ok. I tested with your rp. It seems like your playerhead custom models are out of date. Also, make sure your summon scripts are correct. It looks like the arm textures are being loaded for every part. The texture orientation is correct though which is what I am fixing. You can sanity check by trying the sample summon commands in the repo readme.

maybe explain how the player head models are out of date

**Comment by bradleyq** [comment]
The models were facing the wrong way when I loaded them. I needed to replace them with new ones. They were either modified or out of date. Idk how I can be more clear than that.

**Comment by Creeperz653** [comment]
> The models were facing the wrong way when I loaded them. I needed to replace them with new ones. They were either modified or out of date. Idk how I can be more clear than that.

I used summon command and it looks fine

**Comment by Creeperz653** [comment]
![image](https://github.com/bradleyq/stable_player_display/assets/76449952/9ca26ac7-11f0-4de8-812f-f24f4ba7d18b)
its not resolved something is effecting the textures it should be arm textures but its not for this person it should be consistent
